version: '3.7'

services:

  test_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=test_db
    ports:
      - '5432:5432'

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /Users/ryum/IdeaProjects/ClientCentre_2/ClientProfileFacade/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml



  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin